const poems = [
    "You have a way of turning the simplest days into something magical.",
    "You bring joy into my life every day.",
    "I love you more than you could ever know.",
    "Forever and always.",
    "I'm the luckiest person in the world because I have you.",
    "The day I met you I forgot a life without you.",
    "Wherever I see beauty, I see parts of you.",
    "Seeing your smile",
    "I may be the poet, but you are always the poem.",
    "I love stargazing. Luckily your eyes sparkle like the stars.",
    "When my arms can't carry you, my heart always will instead.",
    "You're my last thought every evening and my first thought every morning.",
    "I used to hate how deeply I feel, but I love how deeply I feel about you.",
    "I will always be right by your side, simply because I find you to be perfect.",
    "If you could see yourself through my eyes you would never be insecure.",
    "I say I want to give you the world because you already gave it to me by being my girlfriend.",
    "I'm all in because you're all I need.",
    "I love how our collection of memories keeps growing.",
    "Each step we take brings us closer to our future together.",
    "My love for you feels limitless, so don't ever worry about me getting tired of loving you.",
    "You might think you're not doing enough, yet just your presence does more to me than anything else.",
    "We close the distance to then go back. I can't wait for the day we permanently close it.",
    "From the moment we say goodbye, I miss you like the stars miss the sun in the morning sky. But you shine brighter than the stars.",
    "I would give you the sun, even if it meant that I stay in the dark.",
    "You made me fall in love with you, with myself and with life.",
    "With you I'm at peace.",
    "I could fill oceans with the love I have for you.",
    "If I had a flower for every time I thought of you, I could walk through my garden forever.",
    "Your hug is my favorite place. It feels like my home.",
    "If I were to go back and meet my childhood self, I would tell him about you and how excited he should be to meet you.",
    "You are the reason why everyone around me sees me in love.",
    "Magic is real and it's the sparkle in your eyes when you laugh.",
    "Even on your worst days you're the most beautiful girl to me.",
    "You light up my days even in the darkest of nights.",
    "Not seeing you every day is hard, but not having you in my life would be much worse.",
    "You're like a playlist full of my favorite songs. Each word you say is a melody to my ears.",
    "I want to know every little thing about you. I find you so interesting. And I want to love you from every possible angle.",
    "I dream of coming home and finding you there.",
    "Falling in love with you is like hearing the birds chirping at a peaceful morning.",
    "Falling in love with you is like watching the sunset paint the sky in colors you never knew existed.",
    "Inside is a thought of beauty. Outside is a form of beauty. You are both.",
    "I hope you know I go to bed thinking of you and wake up thinking of you.",
    "You have the sweetest soul I've ever seen.",
    "The only feeling stronger than my love for you is the ache that comes with missing you."
];